// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom24.Data;

#nullable disable

namespace Nhom24.Migrations
{
    [DbContext(typeof(Nhom24Context))]
    partial class Nhom24ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom24.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("DonHangID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanPhamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.HasKey("DonHangID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("Nhom24.Models.DanhMucSanPham", b =>
                {
                    b.Property<string>("DanhMucSanPhamID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMucSanPhamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DanhMucSanPhamID");

                    b.ToTable("DanhMucSanPham");
                });

            modelBuilder.Entity("Nhom24.Models.DonHang", b =>
                {
                    b.Property<string>("DonHangID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChiDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDungID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("DonHangID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Nhom24.Models.GioHang", b =>
                {
                    b.Property<string>("NguoiDungID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanPhamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("Nhom24.Models.NganhHang", b =>
                {
                    b.Property<string>("NganhHangID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMucSanPhamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NganhHangName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NganhHangID");

                    b.HasIndex("DanhMucSanPhamID");

                    b.ToTable("NganhHang");
                });

            modelBuilder.Entity("Nhom24.Models.NguoiDung", b =>
                {
                    b.Property<string>("NguoiDungID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDungName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Nhom24.Models.SanPham", b =>
                {
                    b.Property<string>("SanPhamID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaSanPham")
                        .HasColumnType("float");

                    b.Property<string>("MoTaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhHangID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanPhamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.HasKey("SanPhamID");

                    b.HasIndex("NganhHangID");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Nhom24.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Nhom24.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom24.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Nhom24.Models.DonHang", b =>
                {
                    b.HasOne("Nhom24.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Nhom24.Models.GioHang", b =>
                {
                    b.HasOne("Nhom24.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom24.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Nhom24.Models.NganhHang", b =>
                {
                    b.HasOne("Nhom24.Models.DanhMucSanPham", "DanhMucSanPham")
                        .WithMany()
                        .HasForeignKey("DanhMucSanPhamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucSanPham");
                });

            modelBuilder.Entity("Nhom24.Models.SanPham", b =>
                {
                    b.HasOne("Nhom24.Models.NganhHang", "NganhHang")
                        .WithMany()
                        .HasForeignKey("NganhHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHang");
                });
#pragma warning restore 612, 618
        }
    }
}
